if(EXISTS "C:/Users/cui/Workspaces/SSEngine/build-tests/tests/sse_tests[1]_tests.cmake")
  include("C:/Users/cui/Workspaces/SSEngine/build-tests/tests/sse_tests[1]_tests.cmake")
else()
  add_test(sse_tests_NOT_BUILT sse_tests_NOT_BUILT)
endif()
